hosts:
  status.example.org:
    file: status.example.org.json
    key: THIS_IS_THE_API_KEY
    # key:
    #   "/api/v1/status": THIS_IS_THE_API_KEY_FOR_THIS_URL_RULE
    #   "/api/v1/sensors/temperature": THIS_IS_THE_API_KEY_FOR_THIS_URL_RULE
    plugins:
      twitter:
        enabled: true
        access:
          token: THIS_IS_THE_ACCESS_TOKEN
          secret: THIS_IS_THE_ACCESS_SECRET
        consumer:
          key: THIS_IS_THE_CONSUMER_KEY
          secret: THIS_IS_THE_CONSUMER_SECRET
        wordlist:
          name:
            - "The space"
            - "Example space"
      matrix:
        enabled: true
        homeserver: "https://chat.example.org"
        username: "@spacestatus:example.org"
        password: "THIS_IS_THE_MATRIX_USER_PASSWORD"
        room: "!ABCDEFGHIJKLMNOPQR:chat.example.org"
plugins:
  twitter:
    wordlist:
      name:
        - "The space"
      verb:
        - "is"
      state:
        open:
          - "open"
          - "allowing access"
        closed:
          - "closed"
          - "not open anymore"
      adjective:
        open:
          - "magnificent"
          - "imposing"
          - "impressive"
          - "awe-inspiring"
          - "grand"
          - "splendid"
          - "majestic"
          - "monumental"
          - "glorious"
          - "sumptuous"
          - "resplendent"
          - "lavish"
          - "beautiful"
          - "delightful"
          - "lovely"
        closed:
          - "too bad"
          - "ignoble"
          - "inglorious"
          - "dishonorable"
          - "atrocious"
          - "flagitious"
          - "lowly"
          - "imean"
          - "poor"
